import { visit } from 'unist-util-visit';
import type { Root, Link, Text } from 'mdast';
import type { Plugin } from 'unified';

const remarkNoBareAutolinks: Plugin<[], Root> = () => {
  return (tree, file) => {
    const source = String(file.value ?? '');

    visit(tree, 'link', (node: Link, index, parent) => {
      if (!parent || index == null) return;

      const start = node.position?.start.offset;
      const end = node.position?.end.offset;
      if (start == null || end == null) return;

      const raw = source.slice(start, end);

      // Explicit markdown links always contain "](" in the source.
      // Autolinks (bare www./https:// text) never do.
      if (raw.includes('](')) return;

      // This was auto-generated by GFM's autolink-literal rule.
      // Convert it back into plain text.
      const textValue = node.children
        .map((child) => (child.type === 'text' ? (child as Text).value : ''))
        .join('');

      const textNode: Text = { type: 'text', value: textValue };
      parent.children.splice(index, 1, textNode);
    });
  };
};

export default remarkNoBareAutolinks;